### ISSUE TITLE
Echo skips all “YouTube Music” videos

### ISSUE THREAD

**Issue by playday3008** [wes1993/YouTubeForAlexa#10]
I have playlist with 700+ songs collected through YouTube Music app, Amazon Echo can't play them

**Comment by wes1993** [comment]
Hello,

**Comment by wes1993** [comment]
Hello,
Have you tried to use a proxy? There is part of the guide that cover this problem.
Unfortunately there is some sort of limitation in YouTube that the request of one video must be from the same IP of the player.
Some times ago this limitation was for only some videos probably now with all video… I use the proxy so I don’t know now the situation, could you send me the LOG of AWS lambada code?
Bye 
Stefano

**Comment by playday3008** [comment]
It plays regular videos, but refuses music videos (although thanks to this “feature” I found a regular video in my music playlist, because only one video out of 700+ was played)

> could you send me the LOG of AWS lambada code?

I use Alexa-hosted skills, instead of setting up AWS, and it has a “CloudWatch Logs” feature, but it didn't work (IDK why, I'm trying to resolve this problem). BUT I can send to you a zip archive with that skill, you can just import it to test.
Also, try to use my playlist in your setup (https://www.youtube.com/playlist?list=PLzy3568xgMLhrl8CDqH4epolaNH95Hz-H)

> Hello, Have you tried to use a proxy?

No, but I'll try it later

**Comment by playday3008** [comment]
OK, I was fixed logs 
![image](https://user-images.githubusercontent.com/18056374/147412993-c43484e0-0042-405b-aa8e-ac503f0dedaf.png)

**Comment by wes1993** [comment]
Ok,
It’s the YouTube limitation unfortunately, if you try to open the link generated from one PC in your network you will see that receive a unauthorised reply, could you try?

If it this the case the only way is configure a proxy server in your LAN with username and password and setting up the AWS to contact your proxy, so the request come from your network and you could listen the songs ;)

Bye
Stefano

**Comment by playday3008** [comment]
Yep, link return 403 for me

**Comment by playday3008** [comment]
And youtube-dl don't work for me

**Comment by wes1993** [comment]
I have tested your playlist and with my config works like a charm.
Probably you need the proxy to bypass the youtube lock.
I have the proxy infact.
Best Regards
Stefano

**Comment by wes1993** [comment]
Have you solved your problem?
