### ISSUE TITLE
skill error

### ISSUE THREAD

**Issue by ghost** [wes1993/YouTubeForAlexa#11]
hello, until a month ago the skill worked perfectly. now when i ask alexa to start youtube she welcomes me without problems, when i say which video to start she says "there was a problem with the response of the required skill". I'm sorry for my bad english because i am italian. kind regards

**Comment by wes1993** [comment]
Ciao,
Anche io sono italiano, ho risolto il problema, aveva nuovamente smesso di funzionare Pytube.
Ora va.
Ciao
Stefano
