### ISSUE TITLE
Si è verificato un errore con la risposta della skill richiesta

### ISSUE THREAD

**Issue by ghost** [wes1993/YouTubeForAlexa#12]
Ciao,  il problema che le ho descritto qualche tempo fa, si è ripresentato. chiedo ad alexa di avviare youtube, mi da il benvenuto. dico di riprodurre il video specifico e alexa risponde si è verificato un errore con la risposta della skill richiesta

**Comment by trinib** [comment]
attualmente lavora per me

**Comment by wes1993** [comment]
Ciao,
c'era un problema con PyTube, nuovamente... ora ho aggiornato e dovrei aver risolto ad ogni modo se vuoi un versione più stabile prova a tenere la variable youtube_dl su true.

Ciao
Stefano

**Comment by ghost** [comment]
ti adoro, funziona
