### ISSUE TITLE
pytube

### ISSUE THREAD

**Issue by ghost** [wes1993/YouTubeForAlexa#13]
ciao. pytube ha smesso di nuovo di funzionare. potresti gentilmente dirmi come attivare la variabile youtube_dl ? io non ci sono riuscito. grazie in anticipo, marco

**Comment by wes1993** [comment]
Ciao, purtroppo non ho avuto molto tempo per stare dietro al progetto, sto preparando una nuova versione che utilizzerà come prima risorsa YouTube-DL invece che PyTube così non dovresti avere più problemi :)
