### ISSUE TITLE
Update  pytube's cipher.py's get_throttling_function_name method

### ISSUE THREAD

**Issue by cristhianviera1** [wes1993/YouTubeForAlexa#14]
When I try to search any video of youtube api throgh the lambda function I get the following error 
[pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple]
 
 I check the version of cipher.py and is 12.0.0
 For me works updating the variable function_patterns of get_throttling_function_name method to `function_patterns=[r'a\.[a-zA-Z]\s*&&\s*\([a-z]\s*=\s*a\.get\("n"\)\)\s*&&\s*\([a-z]\s*=\s*([a-zA-Z0-9$]{2,3})(\[\d+\])?\([a-z]\)']`

**Comment by DavidBerdik** [comment]
I am also hitting a RegexMatchError issue (https://github.com/wes1993/YouTubeForAlexa/issues/15), but this does not seem to resolve the issue for me, unfortunately.

**Comment by wes1993** [comment]
Hello
Unfortunately I don’t have so much time in this moment but I hope I can update the skill in this week… for now you could use the youtube_dl alternative, setting up the variable to true, in the next release I will also put the youtube_dl as default instead of pytube

**Comment by DavidBerdik** [comment]
Thanks for getting back to me! As for the update, that's alright. Take your time.

Unfortunately though, the youtube_dl alternative does not seem to work for me either. What makes this even more confusing is that I don't get any CloudWatch log entries indicating an error either.

**Comment by DavidBerdik** [comment]
As an update to my previous comment, it seems that switching to youtube_dl mode and bumping the Lambda timeout from 20 seconds to 1 minute solves the issue. The latency between making a request and getting a response seems to be rather high.

**Comment by wes1993** [comment]
I have updated and fixed pytube also, for now.
