### ISSUE TITLE
Some videos and playlists do not work. Alexa gives up when trying to load them.

### ISSUE THREAD

**Issue by DavidBerdik** [wes1993/YouTubeForAlexa#16]
It seems that even if you switch this skill to use the more reliable youtube-dl and configure a local network proxy through which stream URLs can be generated, there are certain videos and playlists which do not work. For example, here is a video and playlist that I tried to use unsuccessfully.

- https://youtu.be/awjBLm41xJI
- https://youtube.com/playlist?list=PLjO4QRS_y93NgopKIsv-XRcP88U32pEGv

**Comment by wes1993** [comment]
Hello,
i have tested the video link with pytube adn youtube_dl with proxy and works well.

**Comment by DavidBerdik** [comment]
@wes1993 I haven't tried the video again yet, but the playlist is still not working for me. I think I have a theory as to why. Here's what is logged in CloudWatch when I try to load the playlist:

```
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|   timestamp   |                                                                                                                                                                             |
|---------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
| 1654483289342 | START RequestId: 3bcfbc70-1c2a-4086-b7da-eb336e9568b5 Version: $LATEST                                                                                                      |
| 1654483289597 | [INFO] 2022-06-06T02:41:29.596Z 3bcfbc70-1c2a-4086-b7da-eb336e9568b5 List already exists                                                                                    |
| 1654483289839 | [INFO] 2022-06-06T02:41:29.838Z 3bcfbc70-1c2a-4086-b7da-eb336e9568b5 List already exists                                                                                    |
| 1654483289845 | END RequestId: 3bcfbc70-1c2a-4086-b7da-eb336e9568b5                                                                                                                         |
| 1654483289845 | REPORT RequestId: 3bcfbc70-1c2a-4086-b7da-eb336e9568b5 Duration: 501.42 ms Billed Duration: 502 ms Memory Size: 128 MB Max Memory Used: 51 MB Init Duration: 553.13 ms      |
| 1654483294302 | START RequestId: e3a01c54-262e-41f4-bbdd-97b63484c31c Version: $LATEST                                                                                                      |
| 1654483294305 | [INFO] 2022-06-06T02:41:34.304Z e3a01c54-262e-41f4-bbdd-97b63484c31c (REMOVED FOR BREVITY)                                                                                  |
| 1654483294305 | [INFO] 2022-06-06T02:41:34.305Z e3a01c54-262e-41f4-bbdd-97b63484c31c Looking for: Boston's greatest hits                                                                    |
| 1654483294305 | [INFO] 2022-06-06T02:41:34.305Z e3a01c54-262e-41f4-bbdd-97b63484c31c checking for faves                                                                                     |
| 1654483294785 | [INFO] 2022-06-06T02:41:34.785Z e3a01c54-262e-41f4-bbdd-97b63484c31c checking Boston's Greatest Hits | https://youtube.com/playlist?list=PLjO4QRS_y93NgopKIsv-XRcP88U32pEGv |
| 1654483294785 | [INFO] 2022-06-06T02:41:34.785Z e3a01c54-262e-41f4-bbdd-97b63484c31c match found                                                                                            |
| 1654483294786 | [INFO] 2022-06-06T02:41:34.786Z e3a01c54-262e-41f4-bbdd-97b63484c31c match on t2                                                                                            |
| 1654483312645 | [INFO] 2022-06-06T02:41:52.645Z e3a01c54-262e-41f4-bbdd-97b63484c31c Getting youtube-dl url for https://www.youtube.com/watch?v=h_cqDo7eUts                                 |
| 1654483319825 | [youtube] h_cqDo7eUts: Downloading webpage                                                                                                                                  |
| 1654483320424 | ERROR: Video unavailable                                                                                                                                                    |
| 1654483320424 | This video is not available                                                                                                                                                 |
| 1654483320424 | [INFO] 2022-06-06T02:42:00.424Z e3a01c54-262e-41f4-bbdd-97b63484c31c h_cqDo7eUts is unavailable                                                                             |
| 1654483320444 | END RequestId: e3a01c54-262e-41f4-bbdd-97b63484c31c                                                                                                                         |
| 1654483320444 | REPORT RequestId: e3a01c54-262e-41f4-bbdd-97b63484c31c Duration: 26140.28 ms Billed Duration: 26141 ms Memory Size: 128 MB Max Memory Used: 81 MB                           |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

As you can see, it is trying to load a video that is not available. Sure enough, when I open the playlist, there is a notification at the top stating that 3 unavailable videos are hidden.

![image](https://user-images.githubusercontent.com/7663225/172086278-1f281128-5a13-4708-bc73-d4df0bf98343.png)

If I click the "Show Unavailable Videos" toggle, it becomes clear that 2 of the 3 blocked videos are the first two in the playlist. What I suspect is happening is that the blocked video is causing the skill to fail.

![image](https://user-images.githubusercontent.com/7663225/172086530-b46e9be0-eb65-4c28-a1e0-0e030247363a.png)

Considering that you are not encountering this issue when trying to load the playlist, I am guessing that the videos that are blocked for me are not blocked where you live.

To further support this point, attempting to directly visit the video URL referenced in the above log results in this error:

![image](https://user-images.githubusercontent.com/7663225/172087096-cdb73d76-fc95-49fe-b030-61508332cd73.png)

**Comment by DavidBerdik** [comment]
@wes1993 Regarding the video, I tried again and it still does not work. I think the issue may be that Alexa times out on waiting for a response before youtube-dl has time to load the stream. My reason for believing this is because when I made this test request, I tried watching the CloudWatch output while the Echo lights were still flashing, but the echo lights stopped flashing before any entries started getting made in the log related to loading the YouTube URL. I have attached a copy of the output in my CloudWatch log. Could you please investigate this? I am willing to provide assistance with testing if necessary. I should also point out that I am using the proxy configuration, and have verified that it is working properly.

[CloudWatch Log.txt](https://github.com/wes1993/YouTubeForAlexa/files/8841662/CloudWatch.Log.txt)

**Comment by wes1993** [comment]
Could you please try with pytube?
You must wait about 60 second before the song start so please wait after you have send the play command.
Best regards 
Stefano

**Comment by DavidBerdik** [comment]
Unfortunately, PyTube does not seem to work either. As before, the CloudWatch log shows that the song is loading after Alexa has already given up on waiting for the song to start playing.

[CloudWatch Log.txt](https://github.com/wes1993/YouTubeForAlexa/files/8849116/CloudWatch.Log.txt)

**Comment by DavidBerdik** [comment]
@wes1993 So, after doing some further research, it seems that my attempt at switching to PyTube two weeks ago did not actually work because of a mistake I made when setting the environment variable. After trying again, it seems that PyTube does work better, although the playlist that has the several blocked videos that I mentioned earlier is still broken. Whenever I try to load that playlist with PyTube, Alexa responds with "There was a problem with the requested skills response."

I also get the following error in CloudWatch:
```
[ERROR] VideoUnavailable: h_cqDo7eUts is unavailable
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 248, in lambda_handler
    return on_intent(event)
  File "/var/task/lambda_function.py", line 264, in on_intent
    return search(event)
  File "/var/task/lambda_function.py", line 1105, in search
    next_url, title = get_url_and_title(id)
  File "/var/task/lambda_function.py", line 850, in get_url_and_title
    return get_url_and_title_pytube(id)
  File "/var/task/lambda_function.py", line 935, in get_url_and_title_pytube
    first_stream = yt.streams.filter(only_audio=True, subtype='mp4').first()
  File "/var/task/pytube/__main__.py", line 295, in streams
    self.check_availability()
  File "/var/task/pytube/__main__.py", line 222, in check_availability
    raise exceptions.VideoUnavailable(video_id=self.video_id)
```

**Comment by DavidBerdik** [comment]
@wes1993 So, after even further research, I believe the problem comes from pytube. There seems to be an issue with handling the `VideoUnavailable` exception. For this skill, I would imagine that we would want to silently skip over unavailable videos that are listed in a playlist, but since this exception crashes the skill even though the skill code is handling it properly as far as I can tell, the skill just breaks.

https://github.com/pytube/pytube/issues/1126

**Comment by DavidBerdik** [comment]
@wes1993 Another update: I finally managed to get the skill to stop crashing when trying to load the Boston playlist! To do this, I updated `get_url_and_title_pytube()`.

```python
def get_url_and_title_pytube(id, retry=True):
#    if 'pytube' in environ and 'http' in environ['pytube']:
#        return get_url_and_title_pytube_server(id)
    from pytube import YouTube
    from pytube.exceptions import LiveStreamError, VideoUnavailable
    proxy_list = {}
    if 'proxy_enabled' in environ and 'proxy' in environ and environ['proxy_enabled'] == 'true':
        logger.info('Using PyTube Proxy')
        proxy_list = {'https': environ['proxy']}
    logger.info('Getting pytube url for https://www.youtube.com/watch?v='+id)
    global video_url
    video_url = "https://www.youtube.com/watch?v="+id
    try:
        yt = YouTube('https://www.youtube.com/watch?v='+id, proxies=proxy_list)
    except LiveStreamError:
        logger.info(id+' is a live video')
        return get_live_video_url_and_title(id)
    except VideoUnavailable:
        logger.info(id+' is unavailable')
        return None, None
    except HTTPError as e:
        logger.info('HTTPError code '+str(e.code))
        if retry:
            return get_url_and_title_youtube_dl(id, False)
        return False, False
    except:
        logger.info('Unable to get URL for '+id)
        return None, None
    
    try:
        yt.check_availability()
    except:
        return None, None

    if video_or_audio[1] == 'video':
        first_stream = yt.streams.filter(progressive=True).first()
    else:
        first_stream = yt.streams.filter(only_audio=True, subtype='mp4').first()
    logger.info(first_stream.url)
    return first_stream.url, first_stream.title
```

The part that I added is this conditional:

```python
    try:
        yt.check_availability()
    except:
        return None, None
```

I am not sure what causes it, but it seems that the exception handling that you use to catch bad video URLs just does not work. I believe that is an issue with pytube. I know this fix is hacky, but at least it gets the job done for now. The only bad news is that even though the skill code no longer crashes, the playlist still never begins to play on Alexa. When I ask for the playlist to load, her lights flicker for about 15 seconds or so and then go out with nothing ever happening.

**Comment by DavidBerdik** [comment]
@wes1993 Another update: I finally managed to get the skill to stop crashing when trying to load the Boston playlist! To do this, I updated `get_url_and_title_pytube()`.

```python
def get_url_and_title_pytube(id, retry=True):
#    if 'pytube' in environ and 'http' in environ['pytube']:
#        return get_url_and_title_pytube_server(id)
    from pytube import YouTube
    from pytube.exceptions import LiveStreamError, VideoUnavailable
    proxy_list = {}
    if 'proxy_enabled' in environ and 'proxy' in environ and environ['proxy_enabled'] == 'true':
        logger.info('Using PyTube Proxy')
        proxy_list = {'https': environ['proxy']}
    logger.info('Getting pytube url for https://www.youtube.com/watch?v='+id)
    global video_url
    video_url = "https://www.youtube.com/watch?v="+id
    try:
        yt = YouTube('https://www.youtube.com/watch?v='+id, proxies=proxy_list)
        yt.check_availability()
    except LiveStreamError:
        logger.info(id+' is a live video')
        return get_live_video_url_and_title(id)
    except VideoUnavailable:
        logger.info(id+' is unavailable')
        logger.info(id + ' ' + str(retry))
        return None, None
    except HTTPError as e:
        logger.info('HTTPError code '+str(e.code))
        if retry:
            return get_url_and_title_youtube_dl(id, False)
        return False, False
    except:
        logger.info('Unable to get URL for '+id)
        return None, None

    if video_or_audio[1] == 'video':
        first_stream = yt.streams.filter(progressive=True).first()
    else:
        first_stream = yt.streams.filter(only_audio=True, subtype='mp4').first()
    logger.info(first_stream.url)
    return first_stream.url, first_stream.title
```

The line that I added was simply:

```python
yt.check_availability()
```

Apparently without that check, there is no way for the exceptions you handle to get triggered.

Although this stops the skill from crashing, the playlist still never begins to play on Alexa. When I ask for the playlist to load, her lights flicker for about 15 seconds or so and then go out with nothing ever happening.

I wonder if perhaps you need to add a [DeferredResponse](https://developer.amazon.com/en-US/docs/alexa/device-apis/alexa-response.html#deferred) to stop the timeout from happening?

**Comment by DavidBerdik** [comment]
I've added a branch to my repo containing this change.

https://github.com/DavidBerdik/YouTubeForAlexa-Lambda/tree/fix-pytube-playlist-crash
