### ISSUE TITLE
Consider adding an environment variable configuration to disable the "Beatles example" when opening the YouTube skill.

### ISSUE THREAD

**Issue by DavidBerdik** [wes1993/YouTubeForAlexa#17]
Whenever you query Alexa to open this skill by saying, "Alexa, open YouTube", she responds with "Welcome to YouTube. Say, for example, play videos by The Beatles." The Beatles example is useful, especially when one is just learning how to use the skill, but once you know how to use the skill, it's rather annoying and pointless. It would be nice if an environment variable could be added to allow for the "Beatles example" to be disabled so that all she says is, "Welcome to YouTube."

**Comment by wes1993** [comment]
Added a variable 
welcome

You should set to short

**Comment by DavidBerdik** [comment]
Thank you! This change is greatly appreciated.
