### ISSUE TITLE
New update not working

### ISSUE THREAD

**Issue by LoryKiller** [wes1993/YouTubeForAlexa#24]
I updated the skill to the latest version but Alexa tells me that there is an error. I went to the logs and saw this:
![image](https://user-images.githubusercontent.com/88860901/220743524-b238b76f-cac4-4a14-948e-87cd50b60aba.png)

**Comment by wes1993** [comment]
Please use this version here.
Remeber that now youtube_dl is really slow so you need to tell two or tre times to alexa to play something or you can use the new YouTube Stream Server (see the wiki)
[YouTubeForAlexaLambda.zip](https://github.com/wes1993/YouTubeForAlexa/files/10808150/YouTubeForAlexaLambda.zip)

**Comment by LoryKiller** [comment]
> Please use this version here. Remeber that now youtube_dl is really slow so you need to tell two or tre times to alexa to play something or you can use the new YouTube Stream Server (see the wiki) [YouTubeForAlexaLambda.zip](https://github.com/wes1993/YouTubeForAlexa/files/10808150/YouTubeForAlexaLambda.zip)

I  can't find the wiki. 
Do I have to set it up all by myself?
If so, is it easy to set up?
