### ISSUE TITLE
i cannot find the file  the zip file containg the code to be run on the aws server 

### ISSUE THREAD

**Issue by Stroov** [wes1993/YouTubeForAlexa#30]
cannot find the code as is mentioned in the steps please help 
https://github.com/wes1993/YouTubeForAlexa/blob/master/YouTubeForAlexaLambda.zip

**Comment by wes1993** [comment]
Go in the release page:

https://github.com/wes1993/YouTubeForAlexa/releases/download/09.02.2023/YouTubeForAlexaLambda.zip
