### ISSUE TITLE
adding videos to favourites

### ISSUE THREAD

**Issue by trinib** [wes1993/YouTubeForAlexa#4]
hey bud..i get the 'favourite' custom playlist to work but when i add a video to my favorites i get "there was a problem with the requested skill response",

**Comment by trinib** [comment]
i say "Alexa, ask YouTube to add this video/playlist/channel to my favorites".. is that correct or im i missing something ?
does it add the video to the playlist i created ?? or just in favourites section  ?

**Comment by trinib** [comment]
this i the error i get 
```
{
    "header": {
        "namespace": "SkillDebugger",
        "name": "CaptureDebuggingInfo",
        "messageId": "8e324858-0a12-4f66-ab98-519df37967ae"
    },
    "payload": {
        "skillId": null,
        "timestamp": "2020-12-19T00:14:12.780Z",
        "dialogRequestId": "3e3c042d-e23e-41b8-af67-36edeb3699cf",
        "skillRequestId": null,
        "type": "ConsideredIntents",
        "content": {
            "intents": [
                {
                    "name": "AddVideoToFavoritesIntent",
                    "confirmationStatus": "NONE",
                    "slots": {}
                },
                {
                    "name": "SkipToIntent",
                    "confirmationStatus": "NONE",
                    "slots": {
                        "hours": {
                            "name": "hours",
                            "value": "?",
                            "confirmationStatus": "NONE",
                            "source": "USER",
                            "slotValue": {
                                "type": "Simple",
                                "value": "?"
                            }
                        }
                    }
                }
            ]
        }
    }
}
```

**Comment by wes1993** [comment]
@trinib
Thanks for your issue
I have seen your message,
as soon as i can i will check

Best Regards
Stefano

**Comment by trinib** [comment]
> @trinib
> Thanks for your issue
> I have seen your message,
> as soon as i can i will check
> 
> Best Regards
> Stefano 

thanks.. thought it would been a easy quick fix.. it was just for my mom to add her songs lol.. I'm satisfied with custom playlist anyways

**Comment by wes1993** [comment]
Finally i have fixed the issue,
if you want you can try and if not work reopen the ticket.
Best Regards

**Comment by trinib** [comment]
yes working thanks ..keep it up ..
