### ISSUE TITLE
Problem beim Skillaufruf

### ISSUE THREAD

**Issue by 1984chris** [wes1993/YouTubeForAlexa#5]
Hallo 
danke für die gute Anleitung. Ich habe aber ein Problem
Wenn ich in der alexa developer console: Alexa öffne youtube eingebe kommt............ Bei der Antwort des angeforderten Skill ist ein Problem aufgetreten zurück.
kannst du mir da weiterhelfen bitte.

Danke im Voraus Gruß Christoph

**Comment by trinib** [comment]
> 
> 
> Hallo
> danke für die gute Anleitung. Ich habe aber ein Problem
> Wenn ich in der alexa developer console: Alexa öffne youtube eingebe kommt............ Bei der Antwort des angeforderten Skill ist ein Problem aufgetreten zurück.
> kannst du mir da weiterhelfen bitte.
> 
> Danke im Voraus Gruß Christoph

Sie haben etwas verpasst, denke ich. Versuchen Sie es Schritt für Schritt von Grund auf neu. Funktioniert hier einwandfrei für mich

**Comment by wes1993** [comment]
@trinib, thanks for help me with the ticket, really appreciate :)

> Hallo
> danke für die gute Anleitung. Ich habe aber ein Problem
> Wenn ich in der alexa developer console: Alexa öffne youtube eingebe kommt............ Bei der Antwort des angeforderten Skill ist ein Problem aufgetreten zurück.
> kannst du mir da weiterhelfen bitte.
> 
> Danke im Voraus Gruß Christoph

Haben Sie auch das Amazon AWS-Verfahren sowie das auf Alexa durchgeführt?

**Comment by trinib** [comment]
@wes1993 no problem ..just love this stuff i guess..teaching myself some python basics hoping ill be good like you one day.

**Comment by wes1993** [comment]
@trinib ask here if you need some help :)

best regards
Stefano

**Comment by 1984chris** [comment]
hallo nochmal,
ich probiere es schon seit einigen tagen und bekomme es nicht zum laufen....
Wenn ich in der alexa developer console: Alexa öffne youtube eingebe kommt............ Bei der Antwort des angeforderten Skill ist ein Problem aufgetreten zurück.
habe alles nach Anleitung gemaycht.

Gruß Christoph

**Comment by trinib** [comment]
> 
> 
> hallo nochmal,
> ich probiere es schon seit einigen tagen und bekomme es nicht zum laufen....
> Wenn ich in der alexa developer console: Alexa öffne youtube eingebe kommt............ Bei der Antwort des angeforderten Skill ist ein Problem aufgetreten zurück.
> habe alles nach Anleitung gemaycht.
> 
> Gruß Christoph

Vielleicht senden Sie ein Protokoll, damit Entwickler das Problem sehen können. Haben Sie Umgebungsvariablen mit DEVELOPER_KEY hinzugefügt und die richtige Region festgelegt?

**Comment by wes1993** [comment]
@1984chris ,
Yes send us some log, you could find logs from Amazon AWS Console, it's called CloudWatch

**Comment by 1984chris** [comment]
@trinib  DEVELOPER_KEY hinzugefügt und die richtige Region festgelegt? hab ich so gemacht.

@wes1993 
hoffe das hilft ihnen weiter
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|   timestamp   |                                                                                                                                                                                                                                                                           message                                                                                                                                                                                                                                                                            |
|---------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 1615574212174 | START RequestId: 598814ff-37b1-4377-bc8c-554a7765d6e2 Version: $LATEST                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 1615574212175 | [ERROR] KeyError: 'permissions' Traceback (most recent call last):   File "/var/task/lambda_function.py", line 242, in lambda_handler     return get_welcome_response(event)   File "/var/task/lambda_function.py", line 354, in get_welcome_response     list_created = create_list(event, 'YouTube')   File "/var/task/lambda_function.py", line 363, in create_list     headers = get_headerslist(event)   File "/var/task/lambda_function.py", line 342, in get_headerslist     if 'consentToken' in event['context']['System']['user']['permissions']:  |
| 1615574212176 | END RequestId: 598814ff-37b1-4377-bc8c-554a7765d6e2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| 1615574212176 | REPORT RequestId: 598814ff-37b1-4377-bc8c-554a7765d6e2 Duration: 2.00 ms Billed Duration: 3 ms Memory Size: 512 MB Max Memory Used: 64 MB Init Duration: 410.43 ms                                                                                                                                                                                                                                                                                                                                                                                           |
| 1615574214947 | START RequestId: fc297828-13fa-4953-8be8-8c5d98d2e382 Version: $LATEST                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 1615574214950 | [INFO] 2021-03-12T18:36:54.950Z fc297828-13fa-4953-8be8-8c5d98d2e382 on_session_ended                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| 1615574214951 | END RequestId: fc297828-13fa-4953-8be8-8c5d98d2e382                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| 1615574214951 | REPORT RequestId: fc297828-13fa-4953-8be8-8c5d98d2e382 Duration: 1.73 ms Billed Duration: 2 ms Memory Size: 512 MB Max Memory Used: 64 MB                                                                                                                                                                                                                                                                                                                                                                                                                    |
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by trinib** [comment]
> 
> 
> @trinib DEVELOPER_KEY hinzugefügt und die richtige Region festgelegt? hab ich so gemacht.
> ## @wes1993
> hoffe das hilft ihnen weiter
> timestamp 	message
> 1615574212174 	START RequestId: 598814ff-37b1-4377-bc8c-554a7765d6e2 Version: $LATEST
> 1615574212175 	[ERROR] KeyError: 'permissions' Traceback (most recent call last):   File "/var/task/lambda_function.py", line 242, in lambda_handler     return get_welcome_response(event)   File "/var/task/lambda_function.py", line 354, in get_welcome_response     list_created = create_list(event, 'YouTube')   File "/var/task/lambda_function.py", line 363, in create_list     headers = get_headerslist(event)   File "/var/task/lambda_function.py", line 342, in get_headerslist     if 'consentToken' in event['context']['System']['user']['permissions']:
> 1615574212176 	END RequestId: 598814ff-37b1-4377-bc8c-554a7765d6e2
> 1615574212176 	REPORT RequestId: 598814ff-37b1-4377-bc8c-554a7765d6e2 Duration: 2.00 ms Billed Duration: 3 ms Memory Size: 512 MB Max Memory Used: 64 MB Init Duration: 410.43 ms
> 1615574214947 	START RequestId: fc297828-13fa-4953-8be8-8c5d98d2e382 Version: $LATEST
> 1615574214950 	[INFO] 2021-03-12T18:36:54.950Z fc297828-13fa-4953-8be8-8c5d98d2e382 on_session_ended
> 1615574214951 	END RequestId: fc297828-13fa-4953-8be8-8c5d98d2e382
> 1615574214951 	REPORT RequestId: fc297828-13fa-4953-8be8-8c5d98d2e382 Duration: 1.73 ms Billed Duration: 2 ms Memory Size: 512 MB Max Memory Used: 64 MB

@wes1993 would it be better to see it from alexa developer console?

![Annotation 2021-03-12 154707](https://user-images.githubusercontent.com/18756975/110990972-69284f00-834a-11eb-8ad9-9f14b5eea344.png)

**Comment by 1984chris** [comment]
![Alexa Developer Console](https://user-images.githubusercontent.com/43066136/110993575-c25aa780-8377-11eb-8033-dfcc5724e6bd.png)

reicht das?

**Comment by trinib** [comment]
> 
> 
> ![Alexa Developer Console](https://user-images.githubusercontent.com/43066136/110993575-c25aa780-8377-11eb-8033-dfcc5724e6bd.png)
> 
> reicht das?

Hmm, ich dachte, ich hätte einen Fehler gesehen. Ich bin mir nicht sicher, was das Problem ist. Meine nächste Vermutung ist, dass Sie in diesem Stadium etwas falsch gemacht haben
![image](https://user-images.githubusercontent.com/18756975/110997735-3420fa00-8354-11eb-861c-d50d37ddc5fc.png)

**Comment by wes1993** [comment]
Sorry if I write in English but I’m on mobile.
I need the AWS Log because I need to see if Alexa call the AWS function 

Best Regards
Stefano

**Comment by 1984chris** [comment]
@trinib  
ich habe alles nochmal kontroliert konnte nichts finden.

@wes1993 
hie ist die cloud watch ich hoffe das ist was sie benötigen.

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|   timestamp   |                                                                                                                                                                                                                                                                           message                                                                                                                                                                                                                                                                            |
|---------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 1615620373222 | START RequestId: 056ef3af-a0e2-4c2e-8288-a3c654a60e05 Version: $LATEST                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 1615620373223 | [ERROR] KeyError: 'permissions' Traceback (most recent call last):   File "/var/task/lambda_function.py", line 242, in lambda_handler     return get_welcome_response(event)   File "/var/task/lambda_function.py", line 354, in get_welcome_response     list_created = create_list(event, 'YouTube')   File "/var/task/lambda_function.py", line 363, in create_list     headers = get_headerslist(event)   File "/var/task/lambda_function.py", line 342, in get_headerslist     if 'consentToken' in event['context']['System']['user']['permissions']:  |
| 1615620373224 | END RequestId: 056ef3af-a0e2-4c2e-8288-a3c654a60e05                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| 1615620373224 | REPORT RequestId: 056ef3af-a0e2-4c2e-8288-a3c654a60e05 Duration: 2.20 ms Billed Duration: 3 ms Memory Size: 512 MB Max Memory Used: 64 MB Init Duration: 417.38 ms                                                                                                                                                                                                                                                                                                                                                                                           |
| 1615620373558 | START RequestId: 4563f26c-4816-45c5-83ef-ae006669581a Version: $LATEST                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 1615620373562 | [INFO] 2021-03-13T07:26:13.561Z 4563f26c-4816-45c5-83ef-ae006669581a on_session_ended                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| 1615620373562 | END RequestId: 4563f26c-4816-45c5-83ef-ae006669581a                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| 1615620373562 | REPORT RequestId: 4563f26c-4816-45c5-83ef-ae006669581a Duration: 1.81 ms Billed Duration: 2 ms Memory Size: 512 MB Max Memory Used: 64 MB                                                                                                                                                                                                                                                                                                                                                                                                                    |
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by wes1993** [comment]
@1984chris try to open the Alexa App, select the skill and in the settings enable the access to List Write e List Read then retry

**Comment by wes1993** [comment]
I need to check also the code but when I come back to home

**Comment by 1984chris** [comment]
I have now checked, write list, read list is activated.
thanks in advance

Greetings Christoph

**Comment by 1984chris** [comment]
@trinib 
ich nutze die YouTubeforAlexa Lambda.zip vom 23.02.2021 welche nutzt du?

**Comment by trinib** [comment]
> @trinib 
> ich nutze die YouTubeforAlexa Lambda.zip vom 23.02.2021 welche nutzt du?

Ich benutze die neueste Version

**Comment by wes1993** [comment]
@1984chris ,
i think i have found the problem, could you try this ZIP?
[YouTubeForAlexa.zip](https://github.com/wes1993/YouTubeForAlexa/files/6134832/YouTubeForAlexa.zip)

**Comment by wes1993** [comment]
And also can you attach here the copy of your lambda function?

**Comment by 1984chris** [comment]
@wes1993  mit dieser .zip funktioniert es sofort.

**Comment by wes1993** [comment]
Ok perfect :)

**Comment by trinib** [comment]
@wes1993 how come the zip im using dont work for him ?

**Comment by wes1993** [comment]
I don’t know, I think a broken upload of the zip,
But I have also changed the access to the folders, Amazon has fixed a Bug.
In the next days a will release a new version

**Comment by trinib** [comment]
> I don’t know, I think a broken upload of the zip,
> But I have also changed the access to the folders, Amazon has fixed a Bug.
> In the next days a will release a new version

oh well.. keep up the good work.. what I would like is a rss or news website Reader skill.. then my life would be complete lol.. I use brief news flash but only 1 rss link website at a time.. if you have a work around to add multiple flash briefing would be cool as well

**Comment by 1984chris** [comment]
Danke nochmal das es jetzt funktioniert.

**Comment by wes1993** [comment]
No problem :)

**Comment by 1984chris** [comment]
Hallo
seit ein paar Tagen funktioniert der skill nicht mehr.
kann mkr wer weiterhelfen bitte?
Danke 
Gruß Christoph

**Comment by wes1993** [comment]
Hello Christoph :-D
I have released an update for fixing this problem ;-D
There is also a new function that inform you if there is a new update available :-D
Just download the ZIP file and upload in the AWS.
Best regards
Stefano

**Comment by 1984chris** [comment]
Danke für die schnelle Hilfe.
Habe jetztz die .zip in die AWS Hochgeladen.
jetzt funktioniert gar nichts mehr....
Wenn ich sage alexa, öffne youtube kommt bei anforderung des skills ist ein Fehler aufgetreten.

**Comment by 1984chris** [comment]
Danke jetzt Funktioniert es.
War mein Fehler.
Gruß Christoph

**Comment by wes1993** [comment]
No problem :)

**Comment by 1984chris** [comment]
Ich verstehe nicht wie ich eine Favoritenliste erstellen kann.
kannst du mir das erklären? 
wenn ich in der alexa app unter listen Youtube nachsehe sehe ich was ich gespielt habe aber keinen link dazu.

**Comment by trinib** [comment]
> 
> 
> Hello Christoph :-D
> I have released an update for fixing this problem ;-D
> There is also a new function that inform you if there is a new update available :-D
> Just download the ZIP file and upload in the AWS.
> Best regards
> Stefano

thats cool lol .. you have any way for me to donate something to you ?

**Comment by wes1993** [comment]
@trinib Thanks a lot for your offer :-D I really appreciate, do you have PayPal?
@1984chris Sorry i don't understand your question, what do you mean with this "wenn ich in der alexa app unter listen Youtube nachsehe sehe ich was ich gespielt habe aber keinen link dazu."?

Best Regrads
Stefano

**Comment by trinib** [comment]
> @trinib Thanks a lot for your offer :-D I really appreciate, do you have PayPal?
> @1984chris Sorry i don't understand your question, what do you mean with this "wenn ich in der alexa app unter listen Youtube nachsehe sehe ich was ich gespielt habe aber keinen link dazu."?
> 
> Best Regrads
> Stefano

yes I do.. I can send email in pm

**Comment by wes1993** [comment]
@trinib if you want you could use this link:
https://www.paypal.com/paypalme/wes93

**Comment by 1984chris** [comment]
ich habe das jetzt mit den Favoriten hinbekommen. habe 2 Playlisten erstellt und bei einer habe ich 6 lieder aber nach dem dritten lied kommt nichts mehr wo kann da der Fehler sein.
Gruß Christoph

**Comment by wes1993** [comment]
@1984chris 
Do you use the proxy or custom API in the AWS variable?

**Comment by trinib** [comment]
@wes1993 did you know you uploaded a zip of the whole git repo instead of the YouTubeForLambda.zip ?

**Comment by wes1993** [comment]
@trinib No, i have checked the YouTubeForAlexaLambda.zip but it's only the lambda and not the Git Repo.
What is this file?

Best Regards
Stefano

**Comment by trinib** [comment]
i mean in "releases" the zip is the repo and in it is lambda function .. i dont know if you want it so , i thought just uploading the function zip only in releases would be easier
![image](https://user-images.githubusercontent.com/18756975/119505866-616a2b00-bd3b-11eb-8600-1ddf2bc8a731.png)

**Comment by wes1993** [comment]
Oh now I have understand.
I have this zip because sometimes I should update the translations but probably I could add in the download section only the lambda outside the zip

**Comment by trinib** [comment]
> Oh now I have understand.
> I have this zip because sometimes I should update the translations but probably I could add in the download section only the lambda outside the zip

Yea not a big deal just someome new to this might upload the whole repo zip in aws lambda like what I did at first lol

**Comment by wes1993** [comment]
Hahaha now I have understand!!
I will do in the next days not so much time now :(

**Comment by 1984chris** [comment]
Nein nutze ich nicht.Gruß ChristophVon meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: wes1993 ***@***.***> Datum: 25.05.21  13:02  (GMT+01:00) An: wes1993/YouTubeForAlexa ***@***.***> Cc: 1984chris ***@***.***>, Mention ***@***.***> Betreff: Re: [wes1993/YouTubeForAlexa] Problem beim Skillaufruf (#5) 
@1984chris
Do you use the proxy or custom API in the AWS variable?

**Comment by 1984chris** [comment]
Hallo du schreibst 
For now Pytube won't work, change in var youtube_dl to true for using this skill.
See docs for details
wo muß ich das eingeben?

Gruß Christoph

**Comment by wes1993** [comment]
Hello,
It is inside the variables in the AWS website. 
You could find more details here:
https://github.com/wes1993/YouTubeForAlexa

Best regards
Stefano

**Comment by 1984chris** [comment]
Ich habe jetzt alles nochmal durchgesehen aber ich finde nichts oder ich sehe kein Beispiel wie ich das machen soll.
Meintest du bei AWS unter Umebungsvariablen youtube_dl  true eingeben?

Danke Gruß Christoph

**Comment by wes1993** [comment]
Sorry, my bad,
Yea same procedure as rapid api but in variables write youtube_dl and set as true

**Comment by 1984chris** [comment]
vielen dank jetzt funktioniert es.

Gruß Christoph

**Comment by 1984chris** [comment]
ich hätte nochg eine frage zu den playlists wenn ich jetzt eine playlist mit test erstelle und 5 songs einfüge fängt die playlist erst beim 2ten lied an und überspringt das erste woran kann das liegen?

Gruß Christoph

**Comment by wes1993** [comment]
Unfortunately this is a limitation of YouTube, for some video YouTube request that the IP of the request must be the same as the player but unfortunately this can’t be possibile because the IP of Alexa is your home and the IP of request come from AWS servers.

to solve this you should read the optional part of the manual (using proxy or custom api)
I don’t recommend the custom API

best regards
Stefano

**Comment by 1984chris** [comment]
Hallo Stefano,

seit ein paar Tagen funktioniert der Youtube Skill nicht mehr. Bekomme immer die Antwort bei Anfrage des Skills ist ein Fehler aufgetreten.
Gruß Christoph

**Comment by wes1993** [comment]
Hello Christoph sorry for my delay but i don't have so much time now :-(
I have tested the skill and works very well are you sure that you have everything correct?

Best Regards
Stefano

**Comment by 1984chris** [comment]
Hallo
bei mir kommt bei jeder anfrage bei der Anforderung des Skills ist ein Fehler aufgetreten.

Gruß Christoph

**Comment by wes1993** [comment]
Hello Chris,
I don’t know why could you post some AWS log? Or something to find the problem? (I habe no problem so probably is something in your config I think.)

Best Regards
Stefano

**Comment by 1984chris** [comment]
Hallo Stefano,

Habe jetzt das update YouTubeForAlexaLambda.zip vom 18.10 reingespielt jetzt funktioniert es.
Vielen Dank

Gruß Christoph
