### ISSUE TITLE
error while trying skill

### ISSUE THREAD

**Issue by Dizz02** [wes1993/YouTubeForAlexa#6]
[ERROR] HTTPError: HTTP Error 404: Not FoundTraceback (most recent call last):  File "/var/task/lambda_function.py", line 248, in lambda_handler    return on_intent(event)  File "/var/task/lambda_function.py", line 264, in on_intent    return search(event)  File "/var/task/lambda_function.py", line 1091, in search    next_url, title = get_url_and_title(id)  File "/var/task/lambda_function.py", line 840, in get_url_and_title    return get_url_and_title_pytube(id)  File "/var/task/lambda_function.py", line 921, in get_url_and_title_pytube    first_stream = yt.streams.filter(only_audio=True, subtype='mp4').first()  File "/var/task/pytube/__main__.py", line 321, in streams    return StreamQuery(self.fmt_streams)  File "/var/task/pytube/__main__.py", line 214, in fmt_streams    if "adaptive_fmts" in self.player_config_args:  File "/var/task/pytube/__main__.py", line 188, in player_config_args    self._player_config_args = self.vid_info  File "/var/task/pytube/__main__.py", line 291, in vid_info    return dict(parse_qsl(self.vid_info_raw))  File "/var/task/pytube/__main__.py", line 109, in vid_info_raw    self._vid_info_raw = request.get(self.vid_info_url)  File "/var/task/pytube/request.py", line 53, in get    response = _execute_request(url, headers=extra_headers, timeout=timeout)  File "/var/task/pytube/request.py", line 37, in _execute_request    return urlopen(request, timeout=timeout)  # nosec  File "/var/lang/lib/python3.7/urllib/request.py", line 222, in urlopen    return opener.open(url, data, timeout)  File "/var/lang/lib/python3.7/urllib/request.py", line 531, in open    response = meth(req, response)  File "/var/lang/lib/python3.7/urllib/request.py", line 641, in http_response    'http', request, response, code, msg, hdrs)  File "/var/lang/lib/python3.7/urllib/request.py", line 569, in error    return self._call_chain(*args)  File "/var/lang/lib/python3.7/urllib/request.py", line 503, in _call_chain    result = func(*args)  File "/var/lang/lib/python3.7/urllib/request.py", line 649, in http_error_default    raise HTTPError(req.full_url, code, msg, hdrs, fp) | [ERROR] HTTPError: HTTP Error 404: Not Found Traceback (most recent call last):   File "/var/task/lambda_function.py", line 248, in lambda_handler     return on_intent(event)   File "/var/task/lambda_function.py", line 264, in on_intent     return search(event)   File "/var/task/lambda_function.py", line 1091, in search     next_url, title = get_url_and_title(id)   File "/var/task/lambda_function.py", line 840, in get_url_and_title     return get_url_and_title_pytube(id)   File "/var/task/lambda_function.py", line 921, in get_url_and_title_pytube     first_stream = yt.streams.filter(only_audio=True, subtype='mp4').first()   File "/var/task/pytube/__main__.py", line 321, in streams     return StreamQuery(self.fmt_streams)   File "/var/task/pytube/__main__.py", line 214, in fmt_streams     if "adaptive_fmts" in self.player_config_args:   File "/var/task/pytube/__main__.py", line 188, in player_config_args     self._player_config_args = self.vid_info   File "/var/task/pytube/__main__.py", line 291, in vid_info     return dict(parse_qsl(self.vid_info_raw))   File "/var/task/pytube/__main__.py", line 109, in vid_info_raw     self._vid_info_raw = request.get(self.vid_info_url)   File "/var/task/pytube/request.py", line 53, in get     response = _execute_request(url, headers=extra_headers, timeout=timeout)   File "/var/task/pytube/request.py", line 37, in _execute_request     return urlopen(request, timeout=timeout) # nosec   File "/var/lang/lib/python3.7/urllib/request.py", line 222, in urlopen     return opener.open(url, data, timeout)   File "/var/lang/lib/python3.7/urllib/request.py", line 531, in open     response = meth(req, response)   File "/var/lang/lib/python3.7/urllib/request.py", line 641, in http_response     'http', request, response, code, msg, hdrs)   File "/var/lang/lib/python3.7/urllib/request.py", line 569, in error     return self._call_chain(*args)   File "/var/lang/lib/python3.7/urllib/request.py", line 503, in _call_chain     result = func(*args)   File "/var/lang/lib/python3.7/urllib/request.py", line 649, in http_error_default     raise HTTPError(req.full_url, code, msg, hdrs, fp)
-- | --

**Comment by wes1993** [comment]
Hello,
There is a problem with PyTube, see the readme and enable YouTube-DL

**Comment by Dizz02** [comment]
Thanks for the heads up. You can mark this as closed 😉 good job on this project btw
