### ISSUE TITLE
No está sonando nada

### ISSUE THREAD

**Issue by nestorlasso** [wes1993/YouTubeForAlexa#7]
{
	"body": {
		"version": "1.0",
		"response": {
			"outputSpeech": {
				"type": "PlainText",
				"text": "No está sonando nada."
			},
			"shouldEndSession": true,
			"type": "_DEFAULT_RESPONSE"
		},
		"sessionAttributes": {}
	}
}

**Comment by wes1993** [comment]
You need to check the AWS log in cloud watch not in Alexa console

**Comment by nestorlasso** [comment]
Thanks
