### ISSUE TITLE
Error 410

### ISSUE THREAD

**Issue by nestorlasso** [wes1993/YouTubeForAlexa#8]
<html>
<body>

Campo | Valor
-- | --
@ingestionTime | 1628118112531
@log | 860081204456:/aws/lambda/MiFuncionYoutube
@logStream | 2021/08/04/[$LATEST]986d2986802b4861b728a788a584f5b2
@message | [ERROR] HTTPError: HTTP Error 410: Gone Traceback (most recent call last):   File "/var/task/lambda_function.py", line 248, in lambda_handler     return on_intent(event)   File "/var/task/lambda_function.py", line 264, in on_intent     return search(event)   File "/var/task/lambda_function.py", line 1091, in search     next_url, title = get_url_and_title(id)   File "/var/task/lambda_function.py", line 840, in get_url_and_title     return get_url_and_title_pytube(id)   File "/var/task/lambda_function.py", line 921, in get_url_and_title_pytube     first_stream = yt.streams.filter(only_audio=True, subtype='mp4').first()   File "/var/task/pytube/__main__.py", line 321, in streams     return StreamQuery(self.fmt_streams)   File "/var/task/pytube/__main__.py", line 214, in fmt_streams     if "adaptive_fmts" in self.player_config_args:   File "/var/task/pytube/__main__.py", line 188, in player_config_args     self._player_config_args = self.vid_info   File "/var/task/pytube/__main__.py", line 291, in vid_info     return dict(parse_qsl(self.vid_info_raw))   File "/var/task/pytube/__main__.py", line 109, in vid_info_raw     self._vid_info_raw = request.get(self.vid_info_url)   File "/var/task/pytube/request.py", line 53, in get     response = _execute_request(url, headers=extra_headers, timeout=timeout)   File "/var/task/pytube/request.py", line 37, in _execute_request     return urlopen(request, timeout=timeout) # nosec   File "/var/lang/lib/python3.7/urllib/request.py", line 222, in urlopen     return opener.open(url, data, timeout)   File "/var/lang/lib/python3.7/urllib/request.py", line 531, in open     response = meth(req, response)   File "/var/lang/lib/python3.7/urllib/request.py", line 641, in http_response     'http', request, response, code, msg, hdrs)   File "/var/lang/lib/python3.7/urllib/request.py", line 569, in error     return self._call_chain(*args)   File "/var/lang/lib/python3.7/urllib/request.py", line 503, in _call_chain     result = func(*args)   File "/var/lang/lib/python3.7/urllib/request.py", line 649, in http_error_default     raise HTTPError(req.full_url, code, msg, hdrs, fp)
@timestamp | 1628118103506

</body>
</html>

**Comment by wes1993** [comment]
Hello @nestorlasso 
Unfortunately in this moment PyTube won't work.
You should use youtube_dl by setting the correct variable in Amazon AWS.
See there for more info: https://github.com/wes1993/YouTubeForAlexa
Same procedure as rapid api but in variables write youtube_dl and set as true
Best Regards
Stefano
