### ISSUE TITLE
Error: sorry I am having trouble

### ISSUE THREAD

**Issue by at113920** [wes1993/YouTubeForAlexa#9]
Since the last update that came a couple weeks ago, its been messed up and gives error 'Sorry, i am having trouble. please try in a little while'.  This happens every time I say 'Alexa, ask 'my tube' to play X. 'my tube' is the invocation in the alexa skill. I now have to launch my tube every time and then say play X.

**Comment by wes1993** [comment]
Sorry, i have lost you issue.
Could you try now?
